version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - OPENAI_API_KEY=your-openai-api-key-here
      - OPENAI_BASE_URL=https://ai.reluv.xyz/v1
      - BIG_MODEL=gemini-2.5-pro
      - MIDDLE_MODEL=qwen-3-coder-480b
      - SMALL_MODEL=gpt-oss-120b
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`cc.reluv.xyz`)"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.tls.certresolver=letsencrypt"
      - "traefik.http.services.proxy.loadbalancer.server.port=8082"

networks:
  traefik:
    external: true
    name: traefik_network
